title: Andy Song # your name (or website title) here
logo: "/images/andysong.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br><br>
  Software Engineer 
  <br><br>
   
  <br><br>
  <a href="https://www.linkedin.com/in/andysong-dsat/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-154876606-1 # your Google Analytics tracking ID here
